services:

  frontend:
    build: ./Application-Code/frontend
    container_name: todo-frontend
    ports:
      - "5173:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://13.201.225.83:3500/api/tasks
    depends_on:
      - backend

  backend:
    build: ./Application-Code/backend
    container_name: todo-backend
    ports:
      - "3500:3500"
    environment:
      - MONGO_CONN_STR=mongodb://mongodb:27017/todo
    depends_on:
      - mongodb

  mongodb:
    image: mongo:8
    container_name: todo-mongodb
    
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
